config/routes.rb
Rails.application.routes.draw do

  root "top#home"

  devise_for :users
  resources :users, only: %i[ show index followings followers ] do
    resources :relationships, only: %i[ create destroy ]
    get :followings, on: :member
    get :followers, on: :member
    resources :board_favorites, only: %i[ index ]
  end
  
  resources :boards, only: %i[ new create show edit update destroy] do
    resources :comments, only: %i[ create edit show update destroy ], shallow: true
  end

  resources :board_favorites, only: %i[ create destroy ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy

  
  validates :name, presence: true, length: {maximum: 50}
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255},
                      format: {with: VALID_EMAIL_REGEX},
                      uniqueness: true, allow_blank: true
  
  VALID_PASSWORD_REGEX =/\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[\d])\w{6,12}\z/
    validates :password, presence: true,
              format: { with: VALID_PASSWORD_REGEX,
              message: "は半角6~12文字英大文字・小文字・数字それぞれ1文字以上含む必要があります"}

  def current_user_in_mypage(params_user_id)
    self.id == params_user_id.to_i
  end

  # フォローする側から中間テーブルへのアソシエーション
  has_many :following_relationships, class_name: "Relationship", foreign_key: :following_id
  # フォローする側からフォローされたユーザーを取得する
  has_many :followings, through: :following_relationships, source: :follower

  # フォローされている側から中間テーブルへのアソシエーション
  has_many :followed_relationships, class_name: "Relationship", foreign_key: :follower_id
  # フォローされている側からフォローしている相手のユーザーを取得する
  has_many :followers, through: :followed_relationships, source: :following

  # あるユーザーが引数で渡されたuserにフォローされているか調べるメソッド
  def is_followed_by?(user)
    followed_relationships.find_by(following_id: user.id).present?
  end

  has_many :board_favorites, dependent: :destroy
  has_many :board_favorited, through: :board_favorites, source: :board
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find(params[:id])
    if current_user.nil?
      @is_user_in_mypage = false
    else
      @is_user_in_mypage = current_user.current_user_in_mypage(params[:id])
    end
  end

  def index
    unless current_user
      @users = User.all
    else
      @users = User.where.not(id: current_user.id)
    end
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followers.html.erb
<div>
  <div>
    <div>
      <h1>FOLLOWERS</h1>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td>
              <% if current_user %>
                <% unless user == current_user %>
                  <% if user.is_followed_by?(current_user) %>
                    <% relationship = Relationship.find_by(following_id: current_user.id, follower_id: user.id) %>
                    <%= button_to "フォロー解除", user_relationship_path(user, relationship), method: :delete %>
                  <% else %>
                    <%= button_to "フォロー", user_relationships_path(user), method: :post %>
                  <% end %>
                <% end %>
              <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<div>
  <div>
    <div>
      <h1>FOLLOWING</h1>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td>
              <% if current_user %>
                <% unless user == current_user %>
                  <% if user.is_followed_by?(current_user) %>
                    <% relationship = Relationship.find_by(following_id: current_user.id, follower_id: user.id) %>
                    <%= button_to "フォロー解除", user_relationship_path(user, relationship), method: :delete %>
                  <% else %>
                    <%= button_to "フォロー", user_relationships_path(user), method: :post %>
                  <% end %>
                <% end %>
              <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div>
  <div>
    <div>
    <h1>全ユーザー</h1>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <strong><%= user.name %></strong>
                <% end %>
              </td>
              <td>
                <%# if current_userでcurrent_userがnilの場合は下記の処理が行われない %>
                <% if current_user %>
                  <% unless user == current_user %>
                    <% if user.is_followed_by?(current_user) %>
                      <% relationship = Relationship.find_by(following_id: current_user.id, follower_id: user.id) %>
                      <%= button_to "フォロー解除", user_relationship_path(user, relationship), method: :delete %>
                    <% else %>
                      <%= button_to "フォロー", user_relationships_path(user), method: :post %>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<section class="container">
      <div class="columns is-multiline">
        <div class="column is-8 is-offset-2 register">
          <div class="columns">
            <div class="column left">
              <h1 class="title is-1"><%= @user.name %></h1>
              <small><%= link_to @user.followings.count, followings_user_path(@user) %>フォロー<%= link_to @user.followers.count, followers_user_path(@user) %>フォロワー</small>
              <h2 class="subtitle colored is-4">募集中の掲示板</h2>
              <% my_boards = @user.boards %>
              <% my_boards.order(updated_at: :desc).limit(5).each do |board| %>
              <p><%= link_to board.title, board_path(board) %></p>
              <small><%= board.updated_at.strftime('%Y/%m/%d %H:%M') %></small>
              <% end %>
            </div>
            <div class="column right has-text-centered">
              <h1 class="title is-4">フォロー機能</h1>
              <% if current_user %>
                <% unless @user == current_user %>
                  <% if @user.is_followed_by?(current_user) %>
                    <% relationship = Relationship.find_by(following_id: current_user.id, follower_id: @user.id) %>
                    <%= button_to "unfollow", user_relationship_path(@user, relationship), method: :delete %>
                  <% else %>
                    <%= button_to "follow", user_relationships_path(@user), method: :post %>
                  <% end %>
                <% end %>
              <% end %>
              <p class="description"></p>
              <form>
                <div class="field">
                  <div class="control">
                    <input class="input is-medium" type="text" placeholder="Name">
                  </div>
                </div>

                <div class="field">
                  <div class="control">
                    <input class="input is-medium" type="email" placeholder="Email">
                  </div>
                </div>
                <button class="button is-block is-primary is-fullwidth is-medium">Submit</button>
                <br />
                <small><%= link_to "お気に入り一覧", user_board_favorites_path(@user), method: :get %></small>
              </form>
            </div>
          </div>
        </div>
        <div class="column is-8 is-offset-2">
          <br>
          <nav class="level">
            <div class="level-left">
              <div class="level-item">
                <span class="icon">
                  <i class="fab fa-twitter"></i>
                </span> &emsp;
                <span class="icon">
                  <i class="fab fa-facebook"></i>
                </span> &emsp;
                <span class="icon">
                  <i class="fab fa-instagram"></i>
                </span> &emsp;
                <span class="icon">
                  <i class="fab fa-github"></i>
                </span> &emsp;
                <span class="icon">
                  <i class="fas fa-envelope"></i>
                </span>
              </div>
            </div>
            <div class="level-right">
              <small class="level-item" style="color: var(--textLight)">
                &copy; Super Cool Website. All Rights Reserved.
              </small>
            </div>
          </nav>
        </div>
      </div>
    </section>

  <style>
    :root {
      --brandColor: hsl(166, 67%, 51%);
      --background: rgb(247, 247, 247);
      --textDark: hsla(0, 0%, 0%, 0.66);
      --textLight: hsla(0, 0%, 0%, 0.33);
    }

    body {
      background: var(--background);
      height: 100vh;
      color: var(--textDark);
    }

    .field:not(:last-child) {
      margin-bottom: 1rem;
    }

    .register {
      margin-top: 10rem;
      background: white;
      border-radius: 10px;
    }

    .left,
    .right {
      padding: 4.5rem;
    }

    .left {
      border-right: 5px solid var(--background);
    }

    .left .title {
      font-weight: 800;
      letter-spacing: -2px;
    }

    .left .colored {
      color: var(--brandColor);
      font-weight: 500;
      margin-top: 1rem !important;
      letter-spacing: -1px;
    }

    .left p {
      color: var(--textLight);
      font-size: 1.15rem;
    }

    .right .title {
      font-weight: 800;
      letter-spacing: -1px;
    }

    .right .description {
      margin-top: 1rem;
      margin-bottom: 1rem !important;
      color: var(--textLight);
      font-size: 1.15rem;
    }

    .right small {
      color: var(--textLight);
    }

    input {
      font-size: 1rem;
    }

    input:focus {
      border-color: var(--brandColor) !important;
      box-shadow: 0 0 0 1px var(--brandColor) !important;
    }

    .fab,
    .fas {
      color: var(--textLight);
      margin-right: 1rem;
    }

  </style>