config/routes.rb
Rails.application.routes.draw do

  root "top#home"

  devise_for :users
  resources :users, only: %i[ show index followings followers ] do
    resources :relationships, only: %i[ create destroy ]
    get :followings, on: :member
    get :followers, on: :member
    resources :board_favorites, only: %i[ index ]
  end
  
  resources :boards, only: %i[ new create show edit update destroy] do
    resources :comments, only: %i[ create edit show update destroy ], shallow: true
  end

  resources :board_favorites, only: %i[ create destroy ]
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :board_favorites, dependent: :destroy

  validates :title, presence: true

  def is_favorited_by?(user)
    # selfにはboardが入る
    # board = Board.find(1)
    # board.is_favorited_by?(user)
    # すでに特定されているボードに対してメソッドを使用しているので自動的にselfにboardが格納される
    BoardFavorite.where(user_id: user.id, board_id: self.id).exists?
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def new
    @board = Board.new
  end

  def create
    if current_user.nil?
      redirect_to user_session_path
      return
    end
    
    @board = current_user.boards.build(board_params)

    if @board.save  
      redirect_to board_path(@board)
    else
      redirect_to new_board_path
    end
  end

  def show
    @board = Board.find_by(id: params[:id])

    return if current_user.nil?
    @board_favorite = BoardFavorite.find_by(user_id: current_user.id, board_id: @board.id)

    if @board.nil?
      redirect_to boards_path
    else
      @comment = Comment.new(board_id: @board.id)
    end
  end

  def edit
    if current_user.nil?
      redirect_to user_session_path
      return
    end
    # find_byで検索をかけて存在しないidが代入された場合はnilが返る
    @board = Board.find_by(id: params[:id])

    if @board.nil?
      redirect_to new_board_path 
      return
    end

    unless current_user.id == @board.user_id 
      redirect_to new_board_path
    end
  end

  def update
    
    return if current_user.nil?

    @board = Board.find_by(id: params[:id])

    return if @board.nil?

    if current_user.id == @board.user_id
      @board.update!(board_params)
      redirect_to board_path(@board)
    end
  end

  def destroy

    return if current_user.nil?

    @board = Board.find_by(id: params[:id])

    return if @board.nil?

    if current_user.id == @board.user_id
      @board.destroy!
      redirect_to boards_path
    end
  end

  private

  def board_params
    params.require(:board).permit( :title, :img, :description)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/edit.html.erb
<h1>編集画面</h1>
<h2>edit.html.erb</h2>

<%= form_with(model: @board, url:board_path ) do |f|%>

<div class="field">
  <%= f.label :タイトル %><br/>
  <%= f.text_field :title %>
</div>

<div class="field">
  <%= f.label :イメージ画像 %><br/>
  <%= f.text_field :img %>
</div>

<div class="field">
  <%= f.label :紹介文 %><br/>
  <%= f.text_area :description, placeholder: "↘️をドラッグすれば画面が広がります" %>
</div>

<div class="actions">
  <%= f.submit "更新" %>
</div>
<% end %>

<%= form_with(model: @board, url: board_path(@board), method: :delete) do |f| %>
  <div class="actions">
    <%= f.submit "削除" %>
  </div>
<% end %>

app/views/boards/new.html.erb
<h1>新規掲示板作成</h1>
<h2>new.html.erb</h2>

<%= form_with(model: @board, url: boards_path) do |f|%>

<div class="field">
  <%= f.label :タイトル %><br/>
  <%= f.text_field :title %>
</div>

<div class="field">
  <%= f.label :イメージ画像 %><br/>
  <%= f.text_field :img %>
</div>

<div class="filed">
  <%= f.label :紹介文 %><br/>
  <%= f.text_area :description, placeholder: "↘️をドラッグすれば画面が広がります" %>
</div>

<div class="actions">
  <%= f.submit "新規投稿" %>
</div>
<% end %>

app/views/boards/show.html.erb
<div class="box">
<h1>掲示板の詳細</h1>

<div>
  <% if current_user %>
    <% if @board_favorite %>
      <%= button_to "お気に入り解除", board_favorite_path(@board_favorite), method: :delete %>
    <% else %>
      <%= button_to "お気に入り登録", board_favorites_path(board_favorite:{board_id: @board.id}), method: :post %>
    <% end %>
  <% end %>
</div>

<%= @board.id %><br>
<%= @board.title %><br>
<%= @board.img%><br>
<%= @board.description %>


<%= form_with(model: @board, url: edit_board_path(@board), method: :get) do |f| %>
  <%= f.submit "編集" %>
<% end %>
<div>
  <ol>
    <% @board.comments.each do |comment| %>
      <li><%= comment.message %></li>
        <%= comment.user.name %>
        <%= comment.created_at.strftime('%Y/%m/%d %H:%M')  %>
    <% end %>
  </ol>
</div>

<%= form_with(model: @comment, url: board_comments_path(@board)) do |f|%>

<div class="filed">
  <%= f.label :コメント %><br/>
  <%= f.text_field :message, placeholder: "コメントを入力してください" %>
</div>

<div class="actions">
  <%= f.submit "新規投稿" %>
</div>
<% end %>
</div>