config/routes.rb
Rails.application.routes.draw do

  root "top#home"

  devise_for :users
  resources :users, only: %i[ show index followings followers ] do
    resources :relationships, only: %i[ create destroy ]
    get :followings, on: :member
    get :followers, on: :member
    resources :board_favorites, only: %i[ index ]
  end
  
  resources :boards, only: %i[ new create show edit update destroy] do
    resources :comments, only: %i[ create edit show update destroy ], shallow: true
  end

  resources :board_favorites, only: %i[ create destroy ]
end

app/views/layouts/_footer.html.erb
<footer class="footer has-background-dark">
  <div class="content has-text-centered">
  <small class="has-text-white">©︎ kaito hori</small>
  </div>
</footer>
<style>
.footer {
  display: block;
  position: relative;
  height: 50px;
  right: 0;
  bottom: 0;
  left: 0;
}
</style>

app/views/layouts/_header.html.erb
<nav class="navbar is-warning" class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <div class="navbar-item">
      <%= link_to image_tag("linkedin_banner_image_1.png"), root_path%>
    </div>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <div class="navbar-item">
          <strong><%= link_to current_user.name, user_path(current_user) if user_signed_in? %></strong>
      </div>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <div class="navbar-item">
            <%= link_to "会員登録", new_user_registration_path %>
          </div>
          <div class="navbar-item">
            <%= link_to "全ユーザー", users_path %>
          </div>
          <div class="navbar-item">
            <%= link_to "新規投稿", new_board_path %>
          </div>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

  <div class="navbar-end">
    <div class="navbar-item">
      <div class="buttons">
        <div class="button is-primary">
          <% if user_signed_in? %>
            <%= link_to "ログアウト", destroy_user_session_path %>
          <% else %>
            <%= link_to "ログイン", user_session_path%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>